server:
  port: 8080

spring:
  application:
    name: todo-list

  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: root
    password: Manh2004!!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: "oN6jfNmhryVMxezZwZCSBFsaVYwtlrOuya1St5V8z9O2GktgrrkJdbnxx6EZbqWE"
  valid-duration: 1200 # in second